name: bu_statistics
description: BU files statistics.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

executables:
  bu_statistics:

dependencies:
  collection: ^1.16.0
  path: ^1.8.0
  archive: ^3.3.1
  lzma: ^1.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
